
#!/usr/bin/env python3
import json
import datetime
import os
import sys
import argparse
import subprocess
import logging
import math

from matplotlib import lines

# Set up logging.
logger = logging.getLogger(__name__)
# Configure basic logging; level will be adjusted in main() based on args
logging.basicConfig(format="%(levelname)s: %(filename)s:%(lineno)d - %(message)s")

class ConfigurationError(Exception):
    """Custom exception for configuration errors."""
    pass

class Configuration:
    """
    Loads and validates the JSON configuration.
    Handles core settings and the optional PTO percentage distribution.
    NOTE: Updated to support date-range scheduling and no lunch feature.
    """
    def __init__(self, config_path):
        logger.debug(f"Initializing Configuration with path: {config_path}")
        self.config_path = config_path
        self.data = self._load_config()
        self._validate_config()
        logger.debug("Configuration loaded and validated successfully.")

    def _load_config(self):
        logger.debug(f"Attempting to load config file: {self.config_path}")
        if not os.path.exists(self.config_path):
            logger.error(f"Configuration file '{self.config_path}' not found. It should have been generated by the main script.")
            raise ConfigurationError(f"Configuration file '{self.config_path}' is missing.")

        try:
            logger.debug(f"Opening and reading generated config file: {self.config_path}")
            with open(self.config_path, "r", encoding='utf-8') as f:
                data = json.load(f)
            logger.debug(f"Raw configuration data loaded: {json.dumps(data, indent=2)}")
            return data
        except json.JSONDecodeError as e:
            logger.error(f"Error parsing JSON configuration file '{self.config_path}': {e}", exc_info=True)
            raise ConfigurationError(f"Error parsing JSON configuration file '{self.config_path}': {e}")
        except IOError as e:
            logger.error(f"Error reading configuration file '{self.config_path}': {e}", exc_info=True)
            raise ConfigurationError(f"Error reading configuration file '{self.config_path}': {e}")

    def _validate_config(self):
        logger.debug("Starting configuration validation.")
        required_keys = [
            "projects",
            "workday_start_time",
            "workday_end_time",
            "paid_time_off",
            "start_date",
            "end_date",
            "work_days",
        ]
        missing = [key for key in required_keys if key not in self.data]
        if missing:
            logger.error(f"Missing required configuration keys: {missing}")
            raise ConfigurationError(f"Missing required configuration keys: {', '.join(missing)}")
        logger.debug(f"All required top-level keys present: {required_keys}")

        # Validate data types and value ranges
        if not isinstance(self.paid_time_off, (int, float)) or self.paid_time_off < 0:
            msg = f"'paid_time_off' must be a non-negative number, got: {self.paid_time_off} (type: {type(self.paid_time_off).__name__})"
            logger.error(msg); raise ConfigurationError(msg)
        if not isinstance(self.projects, dict):
            msg = f"'projects' must be a dictionary, got: {type(self.projects).__name__}"
            logger.error(msg); raise ConfigurationError(msg)
        if not isinstance(self.work_days, list) or not all(isinstance(d, str) for d in self.work_days):
            msg = "'work_days' must be a list of weekday names (e.g., ['Monday', 'Tuesday', ...])."
            logger.error(msg); raise ConfigurationError(msg)

        # Validate date formats
        try:
            sd = datetime.date.fromisoformat(self.start_date)
            ed = datetime.date.fromisoformat(self.end_date)
            if sd > ed:
                logger.warning(f"start_date {self.start_date} is after end_date {self.end_date}.")
        except Exception as e:
            msg = f"Invalid date format in 'start_date' or 'end_date'. Use YYYY-MM-DD. Details: {e}"
            logger.error(msg); raise ConfigurationError(msg)

        # Validate work day names
        valid_day_names = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
        invalid_days = [d for d in self.work_days if d not in valid_day_names]
        if invalid_days:
            msg = f"Invalid day names in 'work_days': {invalid_days}. Valid: {valid_day_names}"
            logger.error(msg); raise ConfigurationError(msg)

        # Validate time formats and start<end (use numeric minutes for comparison)
        try:
            t_start = self._parse_time(self.workday_start_time)
            t_end = self._parse_time(self.workday_end_time)
            if t_end <= t_start:
                msg = f"workday_end_time ('{self.workday_end_time}') must be after workday_start_time ('{self.workday_start_time}')."
                logger.error(msg); raise ConfigurationError(msg)
        except ValueError as ve:
            msg = f"Invalid time format. Use 'H:MM AM/PM'. Details: {ve}"
            logger.error(msg); raise ConfigurationError(msg)

        # Validate projects structure
        valid_project_names = set(self.projects.keys())
        logger.debug(f"Defined project names: {valid_project_names}")

        for name, project_cfg in self.projects.items():
            logger.debug(f"Validating project: '{name}'")
            if not isinstance(project_cfg, dict):
                msg = f"Configuration for project '{name}' must be a dictionary, got: {type(project_cfg).__name__}"
                logger.error(msg); raise ConfigurationError(msg)
            if "total_hours" not in project_cfg:
                msg = f"Project '{name}' is missing 'total_hours'."
                logger.error(msg); raise ConfigurationError(msg)
            if not isinstance(project_cfg["total_hours"], (int, float)) or project_cfg["total_hours"] < 0:
                msg = f"'total_hours' for project '{name}' must be a non-negative number, got: {project_cfg['total_hours']} (type: {type(project_cfg['total_hours']).__name__})"
                logger.error(msg); raise ConfigurationError(msg)
            if "speedtype_percentage_distribution" not in project_cfg:
                msg = f"Project '{name}' is missing 'speedtype_percentage_distribution'."
                logger.error(msg); raise ConfigurationError(msg)
            spd = project_cfg["speedtype_percentage_distribution"]
            if not isinstance(spd, dict):
                msg = f"'speedtype_percentage_distribution' for project '{name}' must be a dictionary, got: {type(spd).__name__}"
                logger.error(msg); raise ConfigurationError(msg)

            total_percentage = sum(v for v in spd.values() if isinstance(v, (int, float)))
            logger.debug(f"Project '{name}' speedtype percentages sum: {total_percentage}")
            if not math.isclose(total_percentage, 100.0, abs_tol=0.01):
                msg = f"Speedtype percentages for project '{name}' sum to {total_percentage:.2f}, but should sum to 100."
                logger.error(msg); raise ConfigurationError(msg)

        # Validate PTO distribution (only if PTO>0 and distribution provided)
        pto_dist = self.pto_percentage_distribution
        if pto_dist and self.paid_time_off > 0:
            logger.debug(f"Custom PTO distribution found and PTO > 0: {pto_dist}")
            if not isinstance(pto_dist, dict):
                msg = f"'pto_percentage_distribution' must be a dictionary if provided, got: {type(pto_dist).__name__}"
                logger.error(msg); raise ConfigurationError(msg)
            total_pto_percentage = sum(v for v in pto_dist.values() if isinstance(v, (int, float)))
            logger.debug(f"PTO distribution percentages sum: {total_pto_percentage}")
            if not math.isclose(total_pto_percentage, 100.0, abs_tol=0.01):
                msg = f"PTO distribution percentages sum to {total_pto_percentage:.2f}, not 100."
                logger.error(msg); raise ConfigurationError(msg)
            for pto_proj_name in pto_dist:
                logger.debug(f"Checking PTO distribution project: '{pto_proj_name}'")
                if pto_proj_name not in valid_project_names:
                    msg = f"Project '{pto_proj_name}' in 'pto_percentage_distribution' is not defined in 'projects' (Available: {valid_project_names})."
                    logger.error(msg); raise ConfigurationError(msg)
        elif not pto_dist and self.paid_time_off > 0 and self.projects:
            logger.info("No 'pto_percentage_distribution' provided. PTO will be split equally among defined projects (handled downstream).")
        elif not pto_dist and self.paid_time_off > 0 and not self.projects:
            logger.warning("PTO > 0 configured, but no 'pto_percentage_distribution' provided and no projects are defined for equal splitting.")
        else:
            logger.debug("PTO is 0 or no custom PTO distribution provided.")
        logger.debug("Configuration validation finished successfully.")

    # --- Helpers for time parsing (internal use) ---
    def _parse_time(self, time_str):
        """Parse 'H:MM AM/PM' to minutes since midnight for reliable numeric comparison."""
        try:
            dt = datetime.datetime.strptime(f"1900-01-01 {time_str}", "%Y-%m-%d %I:%M %p")
        except ValueError as e:
            # Re-raise with clearer context for the caller
            raise ValueError(f"Time format error for '{time_str}'. Expected format like 'H:MM AM/PM'.") from e
        return dt.hour * 60 + dt.minute

    # --- Exposed properties ---
    @property
    def projects(self): return self.data["projects"]
    @property
    def workday_start_time(self): return self.data["workday_start_time"]
    @property
    def workday_end_time(self): return self.data["workday_end_time"]
    @property
    def paid_time_off(self): return self.data["paid_time_off"]
    @property
    def pto_percentage_distribution(self): return self.data.get("pto_percentage_distribution", {})
    @property
    def start_date(self): return self.data["start_date"]
    @property
    def end_date(self): return self.data["end_date"]
    @property
    def work_days(self): return self.data["work_days"]


class TimesheetGenerator:
    """
    Generates a single day's schedule based on workday timings and a list of tasks.
    Simplified: no lunch break; one continuous segment.
    """
    def __init__(self, config, minimum_schedule_block_minutes=1.5):
        """
        Initializes the generator, calculating work segments based on configuration.
        """
        logger.debug("Initializing TimesheetGenerator.")
        self.config = config
        self.minimum_schedule_block_minutes = minimum_schedule_block_minutes
        logger.debug(f"Minimum schedulable block minutes set to: {self.minimum_schedule_block_minutes}")

        try:
            logger.debug(f"Parsing workday times: start='{self.config.workday_start_time}', end='{self.config.workday_end_time}'")
            self.workday_start = self._parse_time(self.config.workday_start_time)
            self.workday_end = self._parse_time(self.config.workday_end_time)

            if not self.workday_start < self.workday_end:
                msg = f"Workday start time {self._format_time(self.workday_start)} must be before end time {self._format_time(self.workday_end)}."
                logger.error(msg); raise ConfigurationError(msg)
            self.effective_day_minutes = self.workday_end - self.workday_start
            logger.debug(f"Calculated continuous work segment: Total Effective Minutes/Day={self.effective_day_minutes}")

        except ValueError as e:
            logger.error(f"Invalid time format during parsing: {e}", exc_info=True)
            raise ConfigurationError(f"Invalid time format in configuration: {e}. Expected format like 'H:MM AM/PM'.")

        if self.effective_day_minutes <= 0:
            msg = f"Calculated effective work time per day is zero or negative ({self.effective_day_minutes} min) based on configured timings."
            logger.error(msg); raise ConfigurationError(msg)
        logger.debug("TimesheetGenerator initialized successfully.")

    def _parse_time(self, time_str):
        """Parses H:MM AM/PM format to minutes since midnight."""
        logger.debug(f"Parsing time string: '{time_str}'")
        try:
            dt = datetime.datetime.strptime(f"1900-01-01 {time_str}", "%Y-%m-%d %I:%M %p")
            minutes = dt.hour * 60 + dt.minute
            logger.debug(f"Parsed '{time_str}' to {minutes} minutes since midnight.")
            return minutes
        except ValueError as e:
            logger.debug(f"Failed to parse time string '{time_str}': {e}")
            raise ValueError(f"Time format error for '{time_str}'. Expected format like 'H:MM AM/PM'.")
        
    def _format_duration_hh_mm(self, minutes_float):
        """Formats a duration (in minutes) as H:MM with no text."""
        # Round to nearest minute to avoid floating artifacts
        total_minutes = int(round(minutes_float))
        if total_minutes < 0:
            total_minutes = 0
        hours = total_minutes // 60
        minutes = total_minutes % 60
        return f"{hours}:{minutes:02d}"

    def _format_time(self, minutes_since_midnight):
        """Formats minutes since midnight to H:MM AM/PM string."""
        logger.debug(f"Formatting time for {minutes_since_midnight} minutes since midnight.")
        if minutes_since_midnight < 0:
            logger.warning(f"Attempting to format negative minutes: {minutes_since_midnight}. Returning as is.")
            return f"{minutes_since_midnight} min"
        try:
            total_minutes = int(round(minutes_since_midnight))
            total_minutes = total_minutes % (24 * 60)
            hour_24 = total_minutes // 60
            minute = total_minutes % 60
            period = "AM" if hour_24 < 12 else "PM"
            hour_12 = hour_24 % 12
            if hour_12 == 0: hour_12 = 12
            formatted_time = f"{hour_12}:{minute:02d} {period}"
            logger.debug(f"Formatted {minutes_since_midnight} min to: {formatted_time} (hour_24={hour_24}, hour_12={hour_12}, min={minute}, period='{period}')")
            return formatted_time
        except Exception:
            logger.error(f"Unexpected error formatting time for {minutes_since_midnight} minutes.", exc_info=True)
            return f"ERR_FORMAT({minutes_since_midnight} min)"

    def generate_day(self, day_name, tasks):
        """
        Generates the schedule for one day by processing tasks through a single continuous work segment.
        Modifies the 'tasks' list in place, decrementing remaining minutes.
        """
        logger.debug(f"--- Starting generate_day for '{day_name}' ---")
        logger.debug(f"Initial tasks list for {day_name}: {tasks}")
        lines = []
        current_time_minutes = float(self.workday_start)
        epsilon = 0.01  # Tolerance for float comparisons

        seg_start, seg_end = self.workday_start, self.workday_end
        logger.debug(f"--- Processing segment: 'Workday' from {self._format_time(seg_start)} to {self._format_time(seg_end)} ---")
        current_time_minutes = max(current_time_minutes, float(seg_start))

        while current_time_minutes < seg_end - epsilon and tasks:
            logger.debug(f"Workday loop: current_time={self._format_time(current_time_minutes)}, tasks remaining={len(tasks)}")

            # --- Roll Forward Logic for very short tasks ---
            should_roll_forward = False
            if tasks:
                current_task_name, current_task_minutes = tasks[0]
                if current_task_minutes <= self.minimum_schedule_block_minutes + epsilon:
                    time_available_in_segment = seg_end - current_time_minutes
                    if current_task_minutes <= time_available_in_segment + epsilon and len(tasks) > 1:
                        next_task_name = tasks[1][0]
                        time_to_roll = tasks[0][1]
                        logger.info(f"Rolling forward short task '{current_task_name}' ({time_to_roll:.2f} min) into next task '{next_task_name}'.")
                        tasks[1][1] += time_to_roll
                        tasks.pop(0)
                        should_roll_forward = True
            if should_roll_forward:
                continue
            # --- End Roll Forward Logic ---

            if not tasks:
                logger.debug("No tasks remaining in 'Workday' segment.")
                break

            if tasks[0][1] <= epsilon:
                logger.debug(f"Skipping task '{tasks[0][0]}' with negligible time ({tasks[0][1]:.2f} min). Popping task.")
                tasks.pop(0)
                continue

            task_name, task_minutes = tasks[0]
            time_available_in_segment = seg_end - current_time_minutes
            time_to_schedule = min(task_minutes, time_available_in_segment)

            if time_to_schedule < epsilon:
                current_time_minutes = min(current_time_minutes + epsilon, seg_end)
                continue

            start_time = current_time_minutes
            end_time = current_time_minutes + time_to_schedule

            # Snap to segment end if very close
            if abs(end_time - seg_end) < epsilon:
                end_time = seg_end

            if end_time - start_time >= epsilon:
                formatted_start = self._format_time(start_time)
                formatted_end = self._format_time(end_time)
                lines.append(f"{formatted_start} - {formatted_end}: {task_name}")
                duration_hh_mm = self._format_duration_hh_mm(end_time - start_time)
                lines.append(duration_hh_mm)
                logger.debug(f"Added entry: {formatted_start} - {formatted_end}: {task_name}")

            current_time_minutes = end_time
            tasks[0][1] -= time_to_schedule
            logger.debug(f"Task '{task_name}' remaining time updated to: {tasks[0][1]:.2f} minutes.")

            if tasks[0][1] <= epsilon:
                logger.debug(f"Task '{task_name}' completed. Popping task.")
                tasks.pop(0)

        logger.debug(f"Segment 'Workday' finished at time {self._format_time(current_time_minutes)}.")
        logger.debug(f"--- Finished generate_day for '{day_name}' ---")
        return lines


class TimesheetApp:
    """
    Main application class: Loads config, allocates task times (including PTO),
    and generates the schedule day by day.
    """
    def __init__(self, config_path):
        logger.debug(f"Initializing TimesheetApp with config path: {config_path}")
        self.config = Configuration(config_path)
        self.generator = TimesheetGenerator(self.config, minimum_schedule_block_minutes=1.5)
        self.project_tasks = {}  # Stores {project_name: [[task1, mins], [task2, mins], ...]}
        self._initialize_projects()
        logger.debug("TimesheetApp initialized successfully.")

    def _distribute_rounding_difference(self, tasks, difference, project_name, percentages):
        """Helper to distribute rounding difference minutes intelligently."""
        logger.debug(f"Attempting to distribute {difference} rounding minutes for project '{project_name}'.")
        if difference == 0 or not tasks:
            logger.debug("No rounding difference to distribute or no tasks."); return

        tasks_with_percentage = []
        for i, task_entry in enumerate(tasks):
            task_name = task_entry[0]
            percentage = percentages.get(task_name, 0)
            tasks_with_percentage.append({"index": i, "name": task_name, "percentage": percentage, "current_minutes": task_entry[1]})
            logger.debug(f"  Task for rounding: {task_name}, index: {i}, percentage: {percentage}, current_mins: {task_entry[1]}")

        tasks_with_percentage.sort(key=lambda x: (x["percentage"], x["name"]), reverse=True)
        logger.debug(f"Tasks sorted for rounding distribution: {[t['name'] for t in tasks_with_percentage]}")

        num_tasks = len(tasks_with_percentage)
        distributed = 0
        increment = 1 if difference > 0 else -1
        attempts = 0
        max_attempts = abs(difference) * num_tasks * 2

        while distributed != difference and attempts < max_attempts:
            if num_tasks == 0:
                logger.error(f"Cannot distribute rounding difference for '{project_name}': No tasks available.")
                break
            idx_in_sorted_list = abs(distributed) % num_tasks
            task_info = tasks_with_percentage[idx_in_sorted_list]
            original_task_index = task_info["index"]
            logger.debug(f"Distribution attempt {attempts + 1}: Trying task '{task_info['name']}' (original index {original_task_index})")

            can_adjust = True
            if increment < 0 and tasks[original_task_index][1] <= 0:
                logger.debug(f"Skipping rounding decrement for task '{tasks[original_task_index][0]}' as it already has {tasks[original_task_index][1]} minutes.")
                can_adjust = False

            if can_adjust:
                tasks[original_task_index][1] += increment
                logger.debug(f"Adjusted task '{tasks[original_task_index][0]}' by {increment} min. New total: {tasks[original_task_index][1]}")
                distributed += increment
                logger.debug(f"Total distributed so far: {distributed} / {difference}")
            else:
                logger.debug("Adjustment skipped for this task.")
            attempts += 1

        if distributed != difference:
            logger.error(f"Failed to distribute the full rounding difference for project '{project_name}'. Required: {difference}, Distributed: {distributed}. Allocation may be inaccurate. Check logs. Attempts: {attempts}.")
        else:
            logger.debug(f"Successfully distributed {distributed} rounding minutes for project '{project_name}'.")
        return

    def _initialize_projects(self):
        """Calculates task allocations including PTO and rounding."""
        logger.debug("--- Starting Project Initialization and Task Allocation ---")
        projects_data = self.config.projects
        num_projects = len(projects_data)
        total_pto_hours = self.config.paid_time_off
        pto_distribution = self.config.pto_percentage_distribution
        logger.info(f"Total configured PTO hours: {total_pto_hours}")
        logger.debug(f"Number of projects defined: {num_projects}")
        logger.debug(f"PTO Percentage Distribution config: {pto_distribution}")
        project_pto_hours = {}

        if total_pto_hours > 0:
            if pto_distribution:
                logger.info(f"Using custom PTO distribution from configuration.")
                calculated_total_pto_dist_hours = 0
                for project, percentage in pto_distribution.items():
                    if project in projects_data:
                        hours = total_pto_hours * (percentage / 100.0)
                        project_pto_hours[project] = hours
                        calculated_total_pto_dist_hours += hours
                        logger.debug(f"Project '{project}': Calculated {percentage}% of PTO = {hours:.4f} hours.")
                    else:
                        logger.warning(f"Project '{project}' in PTO distribution not found in main project list '{list(projects_data.keys())}'. Ignoring.")
                if not math.isclose(calculated_total_pto_dist_hours, total_pto_hours, rel_tol=1e-5):
                    logger.warning(f"Sum of calculated distributed PTO hours ({calculated_total_pto_dist_hours:.4f}) doesn't exactly match total configured PTO ({total_pto_hours:.4f}). Likely float precision.")
                else:
                    logger.debug(f"Sum of distributed PTO hours ({calculated_total_pto_dist_hours:.4f}) matches total configured PTO ({total_pto_hours:.4f}).")
            elif num_projects > 0:
                logger.info(f"Distributing {total_pto_hours} PTO hours equally among {num_projects} projects.")
                pto_per_project = total_pto_hours / num_projects
                logger.debug(f"Calculated PTO per project (equal split): {pto_per_project:.4f} hours.")
                for project_name in projects_data:
                    project_pto_hours[project_name] = pto_per_project
            else:
                logger.warning("PTO hours > 0 are configured, but there are no projects defined to allocate them to.")
        else:
            logger.info("Total PTO is 0. No PTO hours will be allocated to projects.")
            for project_name in projects_data:
                project_pto_hours[project_name] = 0.0
        logger.debug(f"Final calculated PTO hours per project: {project_pto_hours}")

        total_minutes_allocated_across_all_projects = 0
        for project_name, cfg in projects_data.items():
            logger.debug(f"--- Processing project: '{project_name}' ---")
            total_hours_proj = cfg["total_hours"]
            pto_hours_for_this_project = project_pto_hours.get(project_name, 0.0)
            logger.debug(f"Project '{project_name}': Total configured hours = {total_hours_proj:.4f}, Allocated PTO hours = {pto_hours_for_this_project:.4f}")
            work_hours = total_hours_proj - pto_hours_for_this_project
            logger.debug(f"Project '{project_name}': Calculated Work hours = {work_hours:.4f}")

            if work_hours < -0.001:
                msg = f"Configuration Error: Project '{project_name}' has negative effective work hours ({work_hours:.2f}). Check config."
                logger.error(msg); raise ConfigurationError(msg)
            elif work_hours < 0:
                logger.warning(f"Project '{project_name}' has slightly negative work hours ({work_hours:.4f}). Clamping to 0.")
                work_hours = 0.0

            total_expected_work_minutes = round(work_hours * 60.0)
            logger.debug(f"Project '{project_name}': Target total work minutes (rounded) = {total_expected_work_minutes}")
            speed_distribution = cfg["speedtype_percentage_distribution"]
            logger.debug(f"Project '{project_name}': Speedtype Distribution = {speed_distribution}")

            project_tasks_list = []
            current_total_integer_minutes = 0
            logger.debug(f"Project '{project_name}': Calculating initial integer minutes for work tasks.")
            for task_name, percentage in speed_distribution.items():
                if not isinstance(percentage, (int, float)) or percentage < 0:
                    logger.warning(f"Task '{task_name}' in project '{project_name}' has invalid percentage ({percentage}). Treating as 0.")
                    percentage = 0.0
                precise_minutes = work_hours * 60.0 * (percentage / 100.0)
                allocated_int = math.floor(precise_minutes)
                project_tasks_list.append([task_name, allocated_int])
                current_total_integer_minutes += allocated_int
                logger.debug(f"  Task '{task_name}' ({percentage}%): Precise={precise_minutes:.4f}, InitialInt={allocated_int}")
            logger.debug(f"Project '{project_name}': Sum of initial integer work minutes = {current_total_integer_minutes}")

            rounding_diff = total_expected_work_minutes - current_total_integer_minutes
            logger.debug(f"Project '{project_name}': Rounding difference for work tasks = {rounding_diff}")
            if rounding_diff != 0:
                logger.debug(f"Project '{project_name}': Distributing rounding difference ({rounding_diff})...")
                self._distribute_rounding_difference(project_tasks_list, rounding_diff, project_name, speed_distribution)
                logger.debug(f"Project '{project_name}': Tasks after rounding distribution: {project_tasks_list}")
            else:
                logger.debug(f"Project '{project_name}': No rounding difference for work tasks.")

            pto_minutes_for_project = round(pto_hours_for_this_project * 60.0)
            logger.debug(f"Project '{project_name}': Calculated PTO minutes (rounded) = {pto_minutes_for_project}")
            if pto_minutes_for_project > 0:
                pto_task_name = "Paid Time Off"
                project_tasks_list.append([pto_task_name, pto_minutes_for_project])
                logger.debug(f"Project '{project_name}': Added '{pto_task_name}' task with {pto_minutes_for_project} minutes.")
            elif pto_minutes_for_project < 0:
                logger.error(f"Project '{project_name}': Calculated negative PTO minutes ({pto_minutes_for_project}). Check config.")

            self.project_tasks[project_name] = project_tasks_list
            logger.debug(f"Project '{project_name}': Final task list stored: {project_tasks_list}")
            final_allocated_minutes_proj = sum(t[1] for t in project_tasks_list)
            total_minutes_allocated_across_all_projects += final_allocated_minutes_proj
            expected_project_total_minutes = round(total_hours_proj * 60.0)
            logger.info(f"Project '{project_name}': Total Hours={total_hours_proj:.2f} (Work={work_hours:.2f}, PTO={pto_hours_for_this_project:.2f}). Allocated Minutes: {final_allocated_minutes_proj} (Expected Total: {expected_project_total_minutes})")
            if final_allocated_minutes_proj != expected_project_total_minutes:
                diff = final_allocated_minutes_proj - expected_project_total_minutes
                logger.warning(f"Project '{project_name}': MISMATCH! Allocated={final_allocated_minutes_proj}, Expected={expected_project_total_minutes}. Diff: {diff}. Check rounding.")
            else:
                logger.debug(f"Project '{project_name}': Allocated minutes match expected.")
            logger.debug(f"--- Finished processing project: '{project_name}' ---")

        logger.debug("--- Final Overall Summary ---")
        # Compute number of work days in the date range
        work_days_set = set(self.config.work_days)
        total_work_days = 0
        try:
            sd = datetime.date.fromisoformat(self.config.start_date)
            ed = datetime.date.fromisoformat(self.config.end_date)
            one_day = datetime.timedelta(days=1)
            d = sd
            while d <= ed:
                if d.strftime('%A') in work_days_set:
                    total_work_days += 1
                d += one_day
        except Exception:
            logger.error("Failed to compute total work days from date range.", exc_info=True)
        total_schedule_capacity_minutes = total_work_days * self.generator.effective_day_minutes
        logger.info(f"Total minutes allocated across all projects: {total_minutes_allocated_across_all_projects}")
        logger.info(f"Total calculated schedule capacity ({total_work_days} days * {self.generator.effective_day_minutes} min/day): {total_schedule_capacity_minutes}")
        if not math.isclose(total_minutes_allocated_across_all_projects, total_schedule_capacity_minutes, abs_tol=1):
            diff = total_minutes_allocated_across_all_projects - total_schedule_capacity_minutes
            logger.warning(f"Potential Mismatch: Allocated minutes ({total_minutes_allocated_across_all_projects}) vs schedule capacity ({total_schedule_capacity_minutes}). Diff: {diff:.2f} min. Check config.")
        else:
            logger.debug("Total allocated project minutes closely match total schedule capacity.")
        logger.debug("--- Finished Project Initialization and Task Allocation ---")

    def _iter_workdays(self):
        """Yield (index, date, weekday_name) for each work day in range [start_date, end_date]."""
        work_days_set = set(self.config.work_days)
        sd = datetime.date.fromisoformat(self.config.start_date)
        ed = datetime.date.fromisoformat(self.config.end_date)
        one_day = datetime.timedelta(days=1)
        i = 0
        d = sd
        while d <= ed:
            weekday_name = d.strftime('%A')
            if weekday_name in work_days_set:
                i += 1
                yield i, d, weekday_name
            d += one_day

    def run(self):
        """Generates the timesheet schedule day by day."""
        logger.debug("--- Starting Timesheet Generation Run ---")

        # Build master task list across projects
        master_task_list = []
        for project_name in sorted(self.project_tasks.keys()):  # Sort for consistent order
            tasks = self.project_tasks[project_name]
            master_task_list.extend([list(task_item) for task_item in tasks])
        logger.debug(f"Created master task list with {len(master_task_list)} items.")

        schedule_output = []
        print("--- Generating Timesheet Schedule ---")

        total_work_days = 0
        for day_index, day_date, day_name in self._iter_workdays():
            total_work_days = day_index
            logger.debug(f"--- Processing Day {day_index} ({day_name} {day_date.isoformat()}) ---")

            schedule_output.append(f"Day {day_index} ({day_name}, {day_date.isoformat()}):")
            logger.debug(f"Tasks list before generating day {day_index}: {master_task_list}")

            if not master_task_list:
                logger.warning(f"No tasks remaining at start of Day {day_index} ({day_name}). Filling with 'Unallocated'.")
                formatted_start = self.generator._format_time(self.generator.workday_start)
                formatted_end = self.generator._format_time(self.generator.workday_end)
                schedule_output.append(f"{formatted_start} - {formatted_end}: Unallocated Time")
            else:
                day_lines = self.generator.generate_day(day_name, master_task_list)  # Modifies master_task_list
                schedule_output.extend(day_lines)
                logger.debug(f"Tasks list after generating day {day_index}: {master_task_list}")

        print("--- Schedule Generation Complete ---")
        logger.debug("--- Checking for Remaining Unscheduled Tasks ---")
        all_tasks_completed = True
        epsilon = 0.1
        actual_remaining_tasks = [[task_name, round(rem_mins, 2)] for task_name, rem_mins in master_task_list if rem_mins > epsilon]

        if actual_remaining_tasks:
            all_tasks_completed = False
            logger.error(f"Tasks remain unscheduled (> {epsilon} min): {actual_remaining_tasks}")
            schedule_output.append(f"WARNING: Some tasks have remaining unscheduled time: {actual_remaining_tasks}")
        else:
            logger.info("All project tasks appear to be fully scheduled within the tolerance.")

        print("--- Populated Timesheet ---")
        for line in schedule_output:
            print(line)

        # --- Calculate and Display Speedtype Totals (exclude PTO) ---
        speedtype_totals_minutes = {}
        for project_name, tasks in self.project_tasks.items():
            for task_name, minutes in tasks:
                if task_name != "Paid Time Off":
                    current_minutes = speedtype_totals_minutes.get(task_name, 0)
                    speedtype_totals_minutes[task_name] = current_minutes + minutes

        print("--- Speedtype Total Hours ---")
        if not speedtype_totals_minutes:
            print("No speedtype hours to report.")
        else:
            sorted_speedtypes = sorted(speedtype_totals_minutes.items(), key=lambda item: item[0])

            for speedtype, total_minutes in sorted_speedtypes:
                hours = int(total_minutes // 60)
                minutes = int(total_minutes % 60)
                print(f"{speedtype}: {hours:02d}:{minutes:02d}")

            grand_total_minutes = sum(speedtype_totals_minutes.values())
            total_hours = int(grand_total_minutes // 60)
            total_rem_minutes = int(grand_total_minutes % 60)

            print("---------------------------------")
            print(f"Total Hours: {total_hours} hours, {total_rem_minutes} minutes")

        logger.debug("--- Timesheet Generation Run Finished ---")


def main():
    """
    Main execution function. Always regenerates the config file from config.py
    before initializing and running the timesheet application.
    """
    parser = argparse.ArgumentParser(description="Generates a daily timesheet schedule based on project/task allocations and PTO.")
    parser.add_argument("--config", type=str, default="config.json", help="Path to configuration JSON file (default: config.json)")
    parser.add_argument("--debug", action="store_true", help="Enable detailed debug logging")
    parser.add_argument("--verbose", "-v", action="store_true", help="Enable informational logging (default)")
    args = parser.parse_args()

    log_level = logging.DEBUG if args.debug else logging.INFO
    logging.basicConfig(level=log_level, format="%(levelname)s: %(filename)s:%(lineno)d - %(message)s", force=True)
    logger.info(f"Logging level set to: {logging.getLevelName(log_level)}")

    config_file_path = args.config
    config_py_path = "config.py"

    # --- Always Regenerate Configuration ---
    try:
        if not os.path.exists(config_py_path):
            logger.critical(f"Error: Cannot regenerate config. '{config_py_path}' not found.")
            print(f"Error: Cannot regenerate config. '{config_py_path}' not found.", file=sys.stderr)
            sys.exit(1)

        logger.info(f"Always regenerating config file ('{config_file_path}') by running {config_py_path}...")
        print(f"Regenerating config file ('{config_file_path}') from {config_py_path}...")

        process = subprocess.run(
            [sys.executable, config_py_path],
            check=True,
            capture_output=True,
            text=True,
            encoding='utf-8'
        )

        logger.debug(f"config.py execution successful. Stdout:{process.stdout}")
        print(process.stdout)  # Show the output from config.py

        if process.stderr:
            logger.warning(f"config.py execution produced stderr:{process.stderr}")
            print(f"Warnings from config.py:{process.stderr}", file=sys.stderr)

    except subprocess.CalledProcessError as e:
        logger.critical(f"Error generating configuration from {config_py_path}: {e}", exc_info=False)
        logger.critical(f"config.py stdout:{e.stdout}")
        logger.critical(f"config.py stderr:{e.stderr}")
        print(f"Error generating config from {config_py_path}: {e}", file=sys.stderr)
        print(f"Output:{e.stdout} Stderr:{e.stderr}", file=sys.stderr)
        sys.exit(1)
    except FileNotFoundError:
        logger.critical(f"Error: '{sys.executable}' command not found. Make sure Python is in your PATH.")
        print(f"Error: '{sys.executable}' command not found. Make sure Python is in your PATH.", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        logger.critical(f"An unexpected error occurred during configuration setup: {e}", exc_info=True)
        print(f"An unexpected error occurred during configuration setup: {e}", file=sys.stderr)
        sys.exit(1)

    # --- Run the Timesheet Application ---
    try:
        logger.debug("Creating TimesheetApp instance.")
        app = TimesheetApp(config_file_path)
        logger.debug("Calling TimesheetApp.run()")
        app.run()
        logger.info("TimesheetApp finished successfully.")
    except ConfigurationError as e:
        logger.error(f"Configuration Error encountered: {e}", exc_info=False)
        print(f"Configuration Error: {e}", file=sys.stderr)
        print("Please check your configuration file ('config.json' or 'config.py').", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        logger.error(f"An unexpected error occurred during application run: {e}", exc_info=True)
        print(f"An unexpected error occurred: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
